services:
  - type: web
    name: omera-django
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --chdir .
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: omera.onrender.com
